fix

diff --git a/setup-buildrc/action.yml b/setup-buildrc/action.yml
--- a/setup-buildrc/action.yml
+++ b/setup-buildrc/action.yml
@@ -6,8 +6,6 @@ runs:
       - name: artifact
         id: artifact
         uses: actions/download-artifact@v3
-        with:
-          name: buildrc-override
       - name: script
         shell: bash
         run: |
@@ -18,11 +16,23 @@ runs:
             mkdir -p temp
             mv "$override_artifact" ./temp/buildrc
           else
-            echo "Override artifact not found. Downloading from GitHub releases..."
+            case "$RUNNER_ARCH" in
+            X64) arch="amd64";;
+            arm) arch="armv7";; # Modify based on your requirements
+            arm64) arch="arm64";;
+            *) echo "Unsupported architecture" && exit 1;;
+            esac
+            os_arch_pattern="${RUNNER_OS,,}-$arch.tar.gz"
+            echo "Override artifact not found. Downloading from GitHub releases... $os_arch_pattern $version"
             # The name of the release file will be 'os-arch.tar.gz'
-            os_arch_pattern="${RUNNER_OS,,}-$RUNNER_ARCH.tar.gz"
-            gh release download --pattern "$os_arch_pattern" --repo nuggxyz/buildrc --dir ./temp/
+          
+            gh release download $version -p "$os_arch_pattern" --repo nuggxyz/buildrc --dir ./temp/
+
+           
             tar -xzf "./temp/$os_arch_pattern" -C ./temp/
+             cd temp/build 
+            ls
+
           fi
 
           # Step 2: Setup alias
@@ -34,4 +44,4 @@ runs:
           echo "buildrc loaded ✅"
         env:
           version: v0.1.2
-          override_artifact: ${{ steps.artifact.outputs.download-path }}/linux-amd64
+          override_artifact: ${{ steps.artifact.outputs.download-path }}/buildrc-override/linux-amd64
